
INSERT INTO daily_page_conversions
(id,borrower_id, email, createdat, environmentname, lastviewedpage, lastcompletedpage, reasonfornotconnectingbank, plaiditemid,
 credit_pulled, credit_we_can_help_with,expenses_finished, offer_generated, connected_account,completed_application,
 utmsource, utmcampaign, utmcontent, utmmedium, utmterm,dmp_enrolled, dmp_firstpaymentdate,dmp_monthlypaymentamount,
 dmp_agreement_signed, dmp_term_in_months, dmp_id, kindofrelief, router)
SELECT id,
       borrower_id,
       email,
       createdat,
       environmentname,
       lastviewedpage,
       lastcompletedpage,
       reasonfornotconnectingbank,
       plaiditemid,
       credit_pulled,
       credit_we_can_help_with,
       expenses_finished,
       offer_generated,
       connected_account,
       completed_application,
       utmsource,
       utmcampaign,
       utmcontent,
       utmmedium,
       utmterm,
       dmp_enrolled,
       dmp_firstpaymentdate,
       dmp_monthlypaymentamount,
       dmp_agreement_signed,
       dmp_term_in_months,
       dmp_id,
       kindofrelief,
       router
FROM staging.staging_finalreport;
