datagenie:
  target: creditgenie_app # this is the DEFAULT target
  outputs:
    creditgenie_app: # this is A target
      type: redshift
      host: "{{ env_var('REDSHIFT_PROD_HOST') }}"
      user: "{{ env_var('REDSHIFT_PROD_USER') }}"
      pass: "{{ env_var('REDSHIFT_PROD_PASS') }}"
      dbname: "{{ env_var('REDSHIFT_PROD_DBNAME') }}"
      port: "{{ env_var('REDSHIFT_PROD_PORT') | as_number }}"
      schema: creditgenie_app # i.e this target will write to creditgenie_app.model_table
      threads: 1
    counselorgenie: # this is ANOTHER target
      type: redshift
      host: "{{ env_var('REDSHIFT_PROD_HOST') }}"
      user: "{{ env_var('REDSHIFT_PROD_USER') }}"
      pass: "{{ env_var('REDSHIFT_PROD_PASS') }}"
      dbname: "{{ env_var('REDSHIFT_PROD_DBNAME') }}"
      port: "{{ env_var('REDSHIFT_PROD_PORT') | as_number }}"
      schema: counselorgenie # i.e this target will write to counselorgenie.model_table
      threads: 1
